### ISSUE TITLE
Do not show error for third party libraries or report portal test stack trace

### ISSUE THREAD

**Issue by Shakevg** [nvborisenko/reportportal-extensions-sourceback#10]
I propose do not show error for third party libraries on report test stack trace.

I have third party libraries (e.g. Microsoft.Exchange.WebServices.Auth.dll) in my project and always extension shows error in stack trace:
```
C:\ReleaseAgent\_work\r4\a\Agent Source AutomationProject\drop\Automation\bin\Release\Microsoft.Exchange.WebServices.Auth.pdb format is not supported. Try to change it to 'portable' or 'embedded'.
C:\ReleaseAgent\_work\r4\a\Agent Source Automation\drop\AutomationProject\bin\Release\Microsoft.Exchange.WebServices.pdb format is not supported. Try to change it to 'portable' or 'embedded'.
```

**Comment by nvborisenko** [comment]
Agreed, thanks for the proposal.
Work to be done:
- Put this message into internal logger as `WARN`
- Update `readme.md` how to view internal logs (Troubleshooting section)
